"""
Error Code Registry

Centralized registry of error codes that can be used across the application
and easily translated on the frontend.
"""

# Authentication Error Codes (1000-1099)
AUTH_INVALID_CREDENTIALS = "AUTH_001"
AUTH_EXPIRED_TOKEN = "AUTH_002"
AUTH_INVALID_TOKEN = "AUTH_003"
AUTH_MISSING_TOKEN = "AUTH_004"
AUTH_INSUFFICIENT_PERMISSIONS = "AUTH_005"

# User Error Codes (1100-1199)
USER_NOT_FOUND = "USER_001"
USER_EMAIL_ALREADY_REGISTERED = "USER_002"
USER_EMAIL_VERIFICATION_FAILED = "USER_003"
USER_INVALID_INPUT = "USER_004"
USER_ALREADY_VERIFIED = "USER_005"

# Resource Error Codes (1200-1299)
RESOURCE_NOT_FOUND = "RES_001"
RESOURCE_ALREADY_EXISTS = "RES_002"
RESOURCE_INVALID_STATE = "RES_003"
RESOURCE_FORBIDDEN = "RES_004"

# Database Error Codes (2000-2099)
DB_INTEGRITY_ERROR = "DB_001"
DB_CONNECTION_ERROR = "DB_002"
DB_QUERY_ERROR = "DB_003"
DB_TRANSACTION_ERROR = "DB_004"

# External Service Error Codes (3000-3099)
EXT_EMAIL_DELIVERY_FAILED = "EXT_001"
EXT_PAYMENT_PROCESSING_FAILED = "EXT_002"
EXT_THIRD_PARTY_ERROR = "EXT_003"

# General Application Error Codes (9000-9099)
GENERAL_VALIDATION_ERROR = "GEN_001"
GENERAL_BUSINESS_RULE_VIOLATION = "GEN_002"
GENERAL_UNEXPECTED_ERROR = "GEN_999"

# Request Validation Error Codes (4000-4099)
REQUEST_INVALID_FORMAT = "REQ_001"
REQUEST_MISSING_FIELD = "REQ_002"
REQUEST_INVALID_VALUE = "REQ_003"
