app:
  name: "name"
  version: "0.0.0"
  api_prefix: "/api/v1"
  log_level: "INFO" 
  log_to_file: true
  log_file: "app/app.log"
  cors:
    origins: ["http://127.0.0.1:5173"]
    allow_credentials: true
    allow_methods: ["*"]
    allow_headers: ["*"]

database:
  url: "postgresql+asyncpg://user:password@localhost:5432/dbname"

jwt:
  algorithm: "RS256"
  access_token_expire_minutes: 60
  private_key_path: "app/keys/private.pem"
  public_key_path: "app/keys/public.pem"