app:
  name: "name"
  version: "0.0.0"
  api_prefix: "/api/v1"
  log_level: "INFO" 
  log_to_file: true
  log_file: "app/app.log"
  environment: "development"
  slow_query_threshold: 1.0
  cors:
    origins: ["http://127.0.0.1:5173", "http://localhost:5173"]
    allow_credentials: true
    allow_methods: ["*"]
    allow_headers: ["*"]

frontend:
  url: "http://localhost:5173"

mail: 
  username: "your_gmail_username@gmail.com"
  password: "your_gmail_password"

database:
  url: "postgresql+asyncpg://user:password@localhost:5432/dbname"

jwt:
  algorithm: "RS256"
  access_token_expire_minutes: 60
  refresh_token_expire_days: 7 
  private_key_path: "app/keys/private.pem"
  public_key_path: "app/keys/public.pem"