"""add user_feed_day, day and feed tables

Revision ID: 3916ba4ebbc5
Revises: fd5d387c3559
Create Date: 2025-08-09 17:05:13.492762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3916ba4ebbc5'
down_revision: Union[str, None] = 'fd5d387c3559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_number', name='uq_day_number'),
    sa.UniqueConstraint('name', name='uq_day_name')
    )
    op.create_index(op.f('ix_day_day_number'), 'day', ['day_number'], unique=True)
    op.create_index(op.f('ix_day_id'), 'day', ['id'], unique=False)
    op.create_table('feed',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_feed_name')
    )
    op.create_index(op.f('ix_feed_id'), 'feed', ['id'], unique=False)
    op.create_table('user_feed_day',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('day_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'feed_id')
    )
    op.create_index(op.f('ix_user_feed_day_day_id'), 'user_feed_day', ['day_id'], unique=False)
    op.create_index(op.f('ix_user_feed_day_feed_id'), 'user_feed_day', ['feed_id'], unique=False)
    op.create_index(op.f('ix_user_feed_day_user_id'), 'user_feed_day', ['user_id'], unique=False)
    op.drop_index('ix_botanical_group_name', table_name='botanical_group')
    op.drop_index('ix_disease_name', table_name='disease')
    op.drop_index('ix_family_name', table_name='family')
    op.drop_index('ix_intervention_name', table_name='intervention')
    op.drop_index('ix_symptom_name', table_name='symptom')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_symptom_name', 'symptom', ['name'], unique=True)
    op.create_index('ix_intervention_name', 'intervention', ['name'], unique=True)
    op.create_index('ix_family_name', 'family', ['name'], unique=True)
    op.create_index('ix_disease_name', 'disease', ['name'], unique=True)
    op.create_index('ix_botanical_group_name', 'botanical_group', ['name'], unique=True)
    op.drop_index(op.f('ix_user_feed_day_user_id'), table_name='user_feed_day')
    op.drop_index(op.f('ix_user_feed_day_feed_id'), table_name='user_feed_day')
    op.drop_index(op.f('ix_user_feed_day_day_id'), table_name='user_feed_day')
    op.drop_table('user_feed_day')
    op.drop_index(op.f('ix_feed_id'), table_name='feed')
    op.drop_table('feed')
    op.drop_index(op.f('ix_day_id'), table_name='day')
    op.drop_index(op.f('ix_day_day_number'), table_name='day')
    op.drop_table('day')
    # ### end Alembic commands ###
