name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies with UV
        working-directory: backend
        run: |
          uv sync

      - name: Lint (ruff)
        run: |
          source .venv/bin/activate
          ruff check --select I
        working-directory: backend

      - name: Verify format (ruff)
        run: |
          source .venv/bin/activate
          ruff format --check
        working-directory: backend

      - name: Type checking (mypy)
        run: |
          source .venv/bin/activate
          mypy .
        working-directory: backend

      - name: Run tests (pytest)
        timeout-minutes: 5
        env:
          ENVIRONMENT: test
          PYTHONUNBUFFERED: 1
        run: |
          source .venv/bin/activate
          # Remove test db if it exists
          if [ -f "test_db.sqlite3" ]; then
            rm test_db.sqlite3
          fi
          # Create file with correct permissions
          touch test_db.sqlite3
          chmod 666 test_db.sqlite3
          # Run tests with verbose output to see where it might hang
          pytest -v --asyncio-mode=strict
        working-directory: backend