name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies with UV
        working-directory: backend
        run: |
          uv sync

      - name: Lint (ruff)
        run: |
          source .venv/bin/activate
          ruff check --select I
        working-directory: backend

      - name: Verify format (ruff)
        run: |
          source .venv/bin/activate
          ruff format --check
        working-directory: backend

      - name: Type checking (mypy)
        run: |
          source .venv/bin/activate
          mypy .
        working-directory: backend

      - name: Run tests (pytest)
        timeout-minutes: 2
        run: |
          source .venv/bin/activate
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest --numprocesses=auto
        working-directory: backend

      - name: Trigger deployment
        if: success() && github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-backend