name: Backend CD

on:
  repository_dispatch:
    types: [deploy-backend]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set lowercase repository name
        run: echo "REPO_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWERCASE }}/backend:latest
            ghcr.io/${{ env.REPO_LOWERCASE }}/backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
    #   - name: Deploy to Render
    #     env:
    #         RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
    #     run: |
    #         curl -X POST $RENDER_DEPLOY_HOOK
