name: Deploy MKDocs with UV to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv --version  # Verify UV installation

    - name: Install dependencies with UV
      run: |
        uv sync  # Install dependencies defined in your UV configuration file

    - name: Verify MkDocs configuration
      run: mkdocs --version && mkdocs serve --strict --no-livereload --watch-theme --watch-theme

    - name: Build MKDocs site
      run: mkdocs build --strict

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site