name: Deploy MKDocs with UV to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv --version  # Verify UV installation

    - name: Install dependencies with UV
      working-directory: docs
      run: |
        uv sync

    - name: Build MKDocs site
      working-directory: docs
      run: |
        source .venv/bin/activate
        mkdocs build --strict

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/site