name: Docs CI/CD.

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.2"

    - name: Install dependencies with UV
      working-directory: docs
      run: |
        uv sync

    - name: Build MKDocs site
      working-directory: docs
      run: |
        source .venv/bin/activate
        mkdocs build --strict

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/site
        enable_jekyll: false