name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 22.14.0
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      - name: Upgrade npm to 10.9.2
        run: npm install -g npm@10.9.2

      - name: Install deps
        run: npm ci
        working-directory: frontend

      - name: Verify Format & Linting
        run: npm run ci:check
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend

      - name: Run tests
        run: npm run test
        working-directory: frontend

      - name: Trigger deployment
        if: success() && github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-frontend